# Generated by Django 5.1.4 on 2024-12-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='questions_asked',
            field=models.ManyToManyField(blank=True, related_name='asked_in_sessions', to='quiz_app.question'),
        ),
    ]
